### PR TITLE
feat: pass ref when creating the component

### PR DESCRIPTION
**Pull request by dugip**

### CODE REVIEW

**Comment by Mokshit06** [comment]
Why is `forwardRef` required in this case? I think if `ref` is passed, wouldn't it also get applied with the rest of the props as normal.

**Comment by dugip** [comment]
@Mokshit06 Here's a reproduction repo:

https://stackblitz.com/edit/vitejs-vite-tfdmq5?file=src%2Fmain.tsx,src%2FDropdown.tsx,src%2FButton.tsx,src%2FApp.tsx

**Comment by Mokshit06** [comment]
@dugip Yeah it looks like `forwardRef` is required as a `ref` passed normally without it doesn't become a part of the `props` object. I'll merge this. Thanks!

**Comment by Mokshit06** [comment]
Should be working in v1.4.0

**Pull request merged**
